# Generated by Django 5.0.14 on 2025-07-01 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationfield',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.application'),
        ),
        migrations.AddField(
            model_name='applicationservice',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.application'),
        ),
        migrations.AddField(
            model_name='enum',
            name='enum_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.enumtag'),
        ),
        migrations.AddField(
            model_name='field',
            name='enum_tag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.enumtag'),
        ),
        migrations.AddField(
            model_name='applicationfield',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.field'),
        ),
        migrations.AddField(
            model_name='field',
            name='field_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.fieldtype'),
        ),
        migrations.AddField(
            model_name='form',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department'),
        ),
        migrations.AddField(
            model_name='field',
            name='form',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.form'),
        ),
        migrations.AddField(
            model_name='application',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.form'),
        ),
        migrations.AddField(
            model_name='form',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.model'),
        ),
        migrations.AddField(
            model_name='form',
            name='parent_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.parentform'),
        ),
        migrations.AddField(
            model_name='service',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.form'),
        ),
        migrations.AddField(
            model_name='applicationservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.service'),
        ),
        migrations.AddField(
            model_name='servicevalue',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.service'),
        ),
        migrations.AddField(
            model_name='form',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.style'),
        ),
    ]
