# Generated by Django 5.2.9 on 2025-12-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="label",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="field",
            name="placeholder",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
