# Generated by Django 5.0.14 on 2025-11-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='required',
        ),
        migrations.AddField(
            model_name='formfield',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
