# Generated by Django 5.0.14 on 2025-10-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SENDED', 'Отправлена'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Выполнена'), ('CANCELLED', 'Отменена'), ('REJECTED', 'Отклонена')], default='SENDED', max_length=32)),
                ('msg', models.CharField(blank=True, default='', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
