# Generated by Django 5.0.14 on 2025-11-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformfield',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
