# Generated by Django 5.0.14 on 2025-10-29 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0002_initial'),
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationformfield',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_fields', to='application.application'),
        ),
        migrations.AddField(
            model_name='applicationformfield',
            name='form_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.formfield'),
        ),
    ]
